name: Jest Coverage Report
on:
    pull_request:
        branches:
            - master
            - main
jobs:
    run-script:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with: 
            node-version: 16.x
        - run: npm run coverage

        

        

